version: '3'

networks:
  apps-network:
    driver: bridge

volumes:
  db_data:

services:

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - apps-network

  wp:
    depends_on:
      - db
    container_name: wp
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # ports:
    #   - 127.0.0.1:8000:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - apps-network

  wpcli:
    depends_on:
      - db
      - wp
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    networks:
      - apps-network

  reverse_proxy:
    depends_on:
      - wp
    image: nginx:1.23.3
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    env_file:
      #(v) env to use for envsubt of templates
      - ./nginx/env/prod.env
    volumes:
      #--- nginx configs 
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates/:/etc/nginx/templates/
      #--- certbot
      # - certbot-etc:/etc/letsencrypt/:ro
      # - certbot-webroot:/var/www/certbot/:ro
    networks:
      - apps-network


